#!/bin/bash -e

case $1 in
  build)
    docker build --no-cache -t passworld .
    ;;

  init)
    mkdir -p .ssh/{,server}
    ./passworld-server new-key
    ;;

  new-key)
    ssh-keygen -t ed25519 -f .ssh/server/id_ed25519 -N ''
    ;;

  passwd)
    docker exec -it passworld passwd passworld
    ;;

  restart)
    ./passworld-server stop "${@:2}"
    ./passworld-server start "${@:2}"
    ;;

  start)
    PASSWORD_AUTH=$([[ "$*" == *"-p"* ]] && echo "yes" || echo "no")

    docker run \
      -d \
      -e "PASSWORD_AUTH=$PASSWORD_AUTH" \
      --name passworld \
      -p 11223:22 \
      -v passworld:/home/passworld \
      -v $PWD/.ssh/server:/root/.ssh:ro \
      passworld

    ./passworld-server passwd
    ;;

  stop)
    docker rm -f passworld

    [[ "$*" == *"-v"* ]] && docker volume rm passworld
    ;;

  *)
    echo $'Usage: passworld-server <command> [OPTIONS] ARGS

Commands:
  build          Build the server image
  init           Setup SSH keys
  restart        Stop and start the container
  start          Start the container
  stop           Stop the container'
    ;;
esac
