#!/bin/bash -e

case $1 in
  copy-id)
    if [[ $# != 2 ]]
    then
      echo "Usage: passworld-client <copy-id> HOSTNAME"
    else
      ssh-copy-id -i .ssh/client/id_ed25519.pub -o "IdentitiesOnly=yes" -p 11223 passworld@"$2"
    fi
    ;;

  init)
    if [[ $# != 2 ]]
    then
      echo "Usage: passworld-client <init> HOSTNAME"
    else
      mkdir -p .ssh/{,client}
      ./passworld-client new-key .ssh/client/id_ed25519
      ./passworld-client copy-id "$2"
    fi
    ;;

  new-key)
    ssh-keygen -t ed25519 -f .ssh/client/id_ed25519 -N ''
    ;;

  ssh)
    if [[ $# != 2 ]]
    then
      echo "Usage: passworld-client <ssh> HOSTNAME"
    else
      ssh -4 -i .ssh/client/id_ed25519 -o "IdentitiesOnly=yes" -p 11223 passworld@"$2"
    fi
    ;;

  wipe-host)
    if [[ $# != 2 ]]
    then
      echo "Usage: passworld-client <wipe-host> HOSTNAME"
    else
      ssh-keygen -R ["$2"]:11223
    fi
    ;;

  *)
    echo $'Usage: passworld-client <command> [OPTIONS] ARGS

Commands:
  init    Setup SSH keys and copy public key to server
  ssh     SSH into the server'

    ;;
esac
