#!/bin/bash

COMMAND=$1
NEXT=$2

case $COMMAND in
  build-server)
    docker build --no-cache -t passworld .
    ;;

  build-start-server)
    PASSWORD_AUTH=$2
    NEXT=$3
    ./run build-server
    ./run start-server "$PASSWORD_AUTH"
    ;;

  clean)
    docker system prune -f
    ;;

  copy-id)
    HOSTNAME=$2
    NEXT=$3
    ssh-copy-id -i ~/.ssh/passworld/client/id_ed25519.pub -p 11223 passworld@"$HOSTNAME"
    ;;

  init-client)
    HOSTNAME=$2
    NEXT=$3
    mkdir -p ~/.ssh/passworld/client
    ./run new-key ~/.ssh/passworld/client/id_ed25519
    ./run copy-id "$HOSTNAME"
    ;;

  init-server)
    mkdir -p ~/.ssh/passworld/server
    ./run new-key ~/.ssh/passworld/server/id_ed25519
    ;;

  new-key)
    FILENAME=$2
    NEXT=$3
    ssh-keygen -t ed25519 -f "$FILENAME" -N ''
    ;;

  passwd)
    docker exec -it passworld passwd passworld
    ;;

  restart-server)
    PASSWORD_AUTH=$2
    NEXT=$3
    ./run stop-server
    ./run start-server "$PASSWORD_AUTH"
    ;;

  rm-volume)
    docker volume rm passworld
    ;;

  start-client)
    HOSTNAME=$2
    NEXT=$3
    ssh -4 -i ~/.ssh/passworld/client/id_ed25519 -p 11223 passworld@"$HOSTNAME"
    ;;

  start-server)
    PASSWORD_AUTH=${2:-"no"}
    NEXT=$3

    docker run \
      -d \
      -e "PASSWORD_AUTH=\"$PASSWORD_AUTH\"" \
      --name passworld \
      -p 11223:22 \
      -v passworld:/home/passworld \
      -v ~/.ssh/passworld/server:/root/.ssh:ro \
      passworld

    ./run passwd
    ;;

  stop-server)
    docker rm -f passworld
    ;;

  wipe-host)
    HOSTNAME=$2
    NEXT=$3
    ssh-keygen -R ["$HOSTNAME"]:11223
    ;;
esac

if [ "$NEXT" ]
then ./run $NEXT
fi
