#!/bin/bash

COMMAND=$1

case $COMMAND in
	build-server)
		docker build --no-cache -t passworld .
		;;
	build-start-server)
		./run build-server
		./run start-server
		;;
	clean)
		docker system prune -f
		;;
	init-client)
		HOSTNAME=$2
		ssh-keygen -t ed25519 -f ~/.ssh/passworld -N ''
		ssh-copy-id -i ~/.ssh/passworld.pub -p 11223 passworld@$HOSTNAME
		;;
	start-client)
		HOSTNAME=$2
		ssh -4 -i ~/.ssh/passworld -p 11223 passworld@$HOSTNAME
		;;
	start-server)
		docker run -d -p 11223:22 --name passworld passworld
		docker exec -it passworld passwd passworld
		;;
	stop-server)
		docker rm -f passworld
		;;
esac
